<?php

use Illuminate\Support\Facades\DB;

DB::table('country_configs')->insert([
    [
        'code' => 'DE',
        'name' => 'Germany',
        'phone_code' => '+49',
        'eu_member' => 1,
        'currency_code' => 'EUR',
        'currency_symbol' => '€',
        'tax_rate' => 19.00,
        'timezone' => 'Europe/Berlin',
        'language_codes' => json_encode(['de']),
        'is_active' => 1,
    ],
    [
        'code' => 'FR',
        'name' => 'France',
        'phone_code' => '+33',
        'eu_member' => 1,
        'currency_code' => 'EUR',
        'currency_symbol' => '€',
        'tax_rate' => 20.00,
        'timezone' => 'Europe/Paris',
        'language_codes' => json_encode(['fr']),
        'is_active' => 1,
    ],
    [
        'code' => 'IT',
        'name' => 'Italy',
        'phone_code' => '+39',
        'eu_member' => 1,
        'currency_code' => 'EUR',
        'currency_symbol' => '€',
        'tax_rate' => 22.00,
        'timezone' => 'Europe/Rome',
        'language_codes' => json_encode(['it']),
        'is_active' => 1,
    ],
    [
        'code' => 'ES',
        'name' => 'Spain',
        'phone_code' => '+34',
        'eu_member' => 1,
        'currency_code' => 'EUR',
        'currency_symbol' => '€',
        'tax_rate' => 21.00,
        'timezone' => 'Europe/Madrid',
        'language_codes' => json_encode(['es']),
        'is_active' => 1,
    ],
    [
        'code' => 'NL',
        'name' => 'Netherlands',
        'phone_code' => '+31',
        'eu_member' => 1,
        'currency_code' => 'EUR',
        'currency_symbol' => '€',
        'tax_rate' => 21.00,
        'timezone' => 'Europe/Amsterdam',
        'language_codes' => json_encode(['nl']),
        'is_active' => 1,
    ],
    [
        'code' => 'BE',
        'name' => 'Belgium',
        'phone_code' => '+32',
        'eu_member' => 1,
        'currency_code' => 'EUR',
        'currency_symbol' => '€',
        'tax_rate' => 21.00,
        'timezone' => 'Europe/Brussels',
        'language_codes' => json_encode(['nl','fr']),
        'is_active' => 1,
    ],
    [
        'code' => 'AT',
        'name' => 'Austria',
        'phone_code' => '+43',
        'eu_member' => 1,
        'currency_code' => 'EUR',
        'currency_symbol' => '€',
        'tax_rate' => 20.00,
        'timezone' => 'Europe/Vienna',
        'language_codes' => json_encode(['de']),
        'is_active' => 1,
    ],
    [
        'code' => 'SE',
        'name' => 'Sweden',
        'phone_code' => '+46',
        'eu_member' => 1,
        'currency_code' => 'SEK',
        'currency_symbol' => 'kr',
        'tax_rate' => 25.00,
        'timezone' => 'Europe/Stockholm',
        'language_codes' => json_encode(['sv']),
        'is_active' => 1,
    ],
    [
        'code' => 'PL',
        'name' => 'Poland',
        'phone_code' => '+48',
        'eu_member' => 1,
        'currency_code' => 'PLN',
        'currency_symbol' => 'zł',
        'tax_rate' => 23.00,
        'timezone' => 'Europe/Warsaw',
        'language_codes' => json_encode(['pl']),
        'is_active' => 1,
    ],
    [
        'code' => 'PT',
        'name' => 'Portugal',
        'phone_code' => '+351',
        'eu_member' => 1,
        'currency_code' => 'EUR',
        'currency_symbol' => '€',
        'tax_rate' => 23.00,
        'timezone' => 'Europe/Lisbon',
        'language_codes' => json_encode(['pt']),
        'is_active' => 1,
    ],
]);