<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountryConfigsSeeder extends Seeder
{
    public function run()
    {
        $configs = [
            [
                'code' => 'GB',
                'name' => 'United Kingdom',
                'phone_code' => '44',
                'eu_member' => false,
                'currency_code' => 'GBP',
                'currency_symbol' => '£',
                'tax_rate' => 20.00,
                'timezone' => 'Europe/London',
                'language_codes' => json_encode(['en']),
                'is_active' => true,
            ],
            [
                'code' => 'FR',
                'name' => 'France',
                'phone_code' => '33',
                'eu_member' => true,
                'currency_code' => 'EUR',
                'currency_symbol' => '€',
                'tax_rate' => 20.00,
                'timezone' => 'Europe/Paris',
                'language_codes' => json_encode(['fr', 'en']),
                'is_active' => true,
            ],
            [
                'code' => 'DE',
                'name' => 'Germany',
                'phone_code' => '49',
                'eu_member' => true,
                'currency_code' => 'EUR',
                'currency_symbol' => '€',
                'tax_rate' => 19.00,
                'timezone' => 'Europe/Berlin',
                'language_codes' => json_encode(['de', 'en']),
                'is_active' => true,
            ],
            [
                'code' => 'IT',
                'name' => 'Italy',
                'phone_code' => '39',
                'eu_member' => true,
                'currency_code' => 'EUR',
                'currency_symbol' => '€',
                'tax_rate' => 22.00,
                'timezone' => 'Europe/Rome',
                'language_codes' => json_encode(['it', 'en']),
                'is_active' => true,
            ],
            [
                'code' => 'ES',
                'name' => 'Spain',
                'phone_code' => '34',
                'eu_member' => true,
                'currency_code' => 'EUR',
                'currency_symbol' => '€',
                'tax_rate' => 21.00,
                'timezone' => 'Europe/Madrid',
                'language_codes' => json_encode(['es', 'en']),
                'is_active' => true,
            ],
            [
                'code' => 'NL',
                'name' => 'Netherlands',
                'phone_code' => '31',
                'eu_member' => true,
                'currency_code' => 'EUR',
                'currency_symbol' => '€',
                'tax_rate' => 21.00,
                'timezone' => 'Europe/Amsterdam',
                'language_codes' => json_encode(['nl', 'en']),
                'is_active' => true,
            ],
            [
                'code' => 'BE',
                'name' => 'Belgium',
                'phone_code' => '32',
                'eu_member' => true,
                'currency_code' => 'EUR',
                'currency_symbol' => '€',
                'tax_rate' => 21.00,
                'timezone' => 'Europe/Brussels',
                'language_codes' => json_encode(['nl', 'fr', 'de']),
                'is_active' => true,
            ],
            [
                'code' => 'PT',
                'name' => 'Portugal',
                'phone_code' => '351',
                'eu_member' => true,
                'currency_code' => 'EUR',
                'currency_symbol' => '€',
                'tax_rate' => 23.00,
                'timezone' => 'Europe/Lisbon',
                'language_codes' => json_encode(['pt', 'en']),
                'is_active' => true,
            ],
            [
                'code' => 'SE',
                'name' => 'Sweden',
                'phone_code' => '46',
                'eu_member' => true,
                'currency_code' => 'SEK',
                'currency_symbol' => 'kr',
                'tax_rate' => 25.00,
                'timezone' => 'Europe/Stockholm',
                'language_codes' => json_encode(['sv', 'en']),
                'is_active' => true,
            ],
            [
                'code' => 'DK',
                'name' => 'Denmark',
                'phone_code' => '45',
                'eu_member' => true,
                'currency_code' => 'DKK',
                'currency_symbol' => 'kr',
                'tax_rate' => 25.00,
                'timezone' => 'Europe/Copenhagen',
                'language_codes' => json_encode(['da', 'en']),
                'is_active' => true,
            ],
            [
                'code' => 'NO',
                'name' => 'Norway',
                'phone_code' => '47',
                'eu_member' => false,
                'currency_code' => 'NOK',
                'currency_symbol' => 'kr',
                'tax_rate' => 25.00,
                'timezone' => 'Europe/Oslo',
                'language_codes' => json_encode(['no', 'en']),
                'is_active' => true,
            ],
            [
                'code' => 'FI',
                'name' => 'Finland',
                'phone_code' => '358',
                'eu_member' => true,
                'currency_code' => 'EUR',
                'currency_symbol' => '€',
                'tax_rate' => 24.00,
                'timezone' => 'Europe/Helsinki',
                'language_codes' => json_encode(['fi', 'sv', 'en']),
                'is_active' => true,
            ],
            [
                'code' => 'IE',
                'name' => 'Ireland',
                'phone_code' => '353',
                'eu_member' => true,
                'currency_code' => 'EUR',
                'currency_symbol' => '€',
                'tax_rate' => 23.00,
                'timezone' => 'Europe/Dublin',
                'language_codes' => json_encode(['en', 'ga']),
                'is_active' => true,
            ],
            [
                'code' => 'PL',
                'name' => 'Poland',
                'phone_code' => '48',
                'eu_member' => true,
                'currency_code' => 'PLN',
                'currency_symbol' => 'zł',
                'tax_rate' => 23.00,
                'timezone' => 'Europe/Warsaw',
                'language_codes' => json_encode(['pl', 'en']),
                'is_active' => true,
            ],
            [
                'code' => 'CH',
                'name' => 'Switzerland',
                'phone_code' => '41',
                'eu_member' => false,
                'currency_code' => 'CHF',
                'currency_symbol' => 'CHF',
                'tax_rate' => 8.10,
                'timezone' => 'Europe/Zurich',
                'language_codes' => json_encode(['de', 'fr', 'it', 'en']),
                'is_active' => true,
            ],
            [
                'code' => 'AT',
                'name' => 'Austria',
                'phone_code' => '43',
                'eu_member' => true,
                'currency_code' => 'EUR',
                'currency_symbol' => '€',
                'tax_rate' => 20.00,
                'timezone' => 'Europe/Vienna',
                'language_codes' => json_encode(['de', 'en']),
                'is_active' => true,
            ],
            [
                'code' => 'CZ',
                'name' => 'Czech Republic',
                'phone_code' => '420',
                'eu_member' => true,
                'currency_code' => 'CZK',
                'currency_symbol' => 'Kč',
                'tax_rate' => 21.00,
                'timezone' => 'Europe/Prague',
                'language_codes' => json_encode(['cs', 'en']),
                'is_active' => true,
            ],
            [
                'code' => 'GR',
                'name' => 'Greece',
                'phone_code' => '30',
                'eu_member' => true,
                'currency_code' => 'EUR',
                'currency_symbol' => '€',
                'tax_rate' => 24.00,
                'timezone' => 'Europe/Athens',
                'language_codes' => json_encode(['el', 'en']),
                'is_active' => true,
            ],
        ];

        foreach ($configs as $config) {
            DB::table('country_configs')->updateOrInsert(
                ['code' => $config['code']],
                $config
            );
        }
    }
}